### PR TITLE
Full fix for propagate uncached type attribute to each member of a struct

### PR DESCRIPTION
**Pull request by petrokarashchenko**
Full fix for propagate uncached type attribute to each member of a struct

### CODE REVIEW

**Comment by petrokarashchenko** [comment]
@claziss could you please take a look.

**Comment by claziss** [comment]
We will include your patch in our nightly builds. I will come back to u if any issue. Thank you for your contribution.

**Comment by petrokarashchenko** [comment]
> We will include your patch in our nightly builds. I will come back to u if any issue. Thank you for your contribution.

@claziss Thank you very much for your help and support! I will wait for your feedback.

**Comment by petrokarashchenko** [comment]
@claziss do you have any update on this?

**Comment by petrokarashchenko** [comment]
@claziss I've been testing this changes locally, and do not observe any issues till now. Could you please evaluate is it possible to include patch into `arc-2019.09`?

**Comment by petrokarashchenko** [comment]
@claziss I have revised my changes and updated to have minimum impact.

**Comment by petrokarashchenko** [comment]
Anyway this changes does not cover the case
```
volatile __attribute__((uncached)) int s[20];

void s_acc(void)
{
    s[10] = 15;
}
```
I'm getting
```
  14               	s_acc:
  15 0000 200A 0F80 		mov	r0,@.LANCHOR0	;14
  15      0000 0000 
  16 0008 D90F      		mov_s	r1,15	;0
  17 000a A02A      		st_s	r1,[r0,40]		;16
  18 000c 7EE0      		j_s	[blink]
```
So I do not see the point of keeping this PR.

**Comment by petrokarashchenko** [comment]
@claziss looking forward to get proper fix from you

**Pull request closed without merging**
