### PR TITLE
libstdc++: Check for fenv.h and complex.h earlier

### PR DESCRIPTION
**Pull request by kolerov**
Initially this check was performed before `GLIBCXX_CHECK_C99_TR1` to prevent detecting `fenv.h` and `complex.h` from C++ headers. But since GCC 14 `GLIBCXX_ENABLE_C99` also tries to check `fenv.h` and finds it C++ headers even if it is not presented in `libc`. Thus, the check must be performed earlier.

### CODE REVIEW

**Comment by artemiy-volkov** [comment]
patch itself is good, but some improvements to the commit message are in order, e.g.
s/Initially/Initially,
s/thise/this
s/presented/present
s/since/, since
s/. Thus//

additionally, I would start the message by mentioning that you're changing configure scripts, I think that makes it easier to put the rest into context

**Comment by kolerov** [comment]
@artemiy-volkov I've updated the commit.

**Comment by artemiy-volkov** [comment]
> @artemiy-volkov I've updated the commit.

Please merge these two sentences:

But, since GCC 14 GLIBCXX_ENABLE_C99 also tries to check fenv.h
and finds it C++ headers even if it is not present in libc.
The check must be performed earlier.

and add "in" before "C++ headers" to fix the grammar:

But, since GCC 14 GLIBCXX_ENABLE_C99 also tries to check fenv.h
and finds it in C++ headers even if it is not present in libc, the check must be performed earlier.

LGTM with that change!

**Comment by kolerov** [comment]
@artemiy-volkov Done!

**Review by artemiy-volkov — APPROVED** [review]

**Review by shahab-vahedi — APPROVED** [review]
This is worth upstreaming Yuriy.

Also, this must be pushed onto `arc64` branch as well.

**Comment by shahab-vahedi** [comment]
@kolerov where is the upstream patch submission?

**Pull request merged**
