### PR TITLE
Clean up: Use TARGET_CPU_DEFAULT for selecting the default processor

### PR DESCRIPTION
**Pull request by claziss**

### CODE REVIEW

**Comment by jeremybennett** [comment]
Thanks for this Claudiu. I'll get Simon and Joern to just check it is OK with them.

**Comment by jeremybennett** [comment]
Hi Claudiu,

Would you commit this, making the minor mod to the ChangeLog suggested by Joern,

Thanks, Jeremy

**Comment by claziss** [comment]
Thanks for the quick review. Tomorrow first hour I will do the changes.

**Comment by claziss** [comment]
Merged.

**Pull request closed without merging**
